// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestosVisites.Infrastructure.Persistence;

#nullable disable

namespace RestosVisites.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RestosVisitesDbContext))]
    [Migration("20260801122431_ConfigurerIdentifiantsCommeNonGeneres")]
    partial class ConfigurerIdentifiantsCommeNonGeneres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CategorieVisite", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VisiteId")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriesId", "VisiteId");

                    b.HasIndex("VisiteId");

                    b.ToTable("VisiteCategories", (string)null);
                });

            modelBuilder.Entity("RestosVisites.Domain.Entities.Categorie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("RestosVisites.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VisiteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VisiteId");

                    b.ToTable("Photos", (string)null);
                });

            modelBuilder.Entity("RestosVisites.Domain.Entities.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Restaurants", (string)null);
                });

            modelBuilder.Entity("RestosVisites.Domain.Entities.Visite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Note")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Note");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Visites", (string)null);
                });

            modelBuilder.Entity("CategorieVisite", b =>
                {
                    b.HasOne("RestosVisites.Domain.Entities.Categorie", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestosVisites.Domain.Entities.Visite", null)
                        .WithMany()
                        .HasForeignKey("VisiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestosVisites.Domain.Entities.Photo", b =>
                {
                    b.HasOne("RestosVisites.Domain.Entities.Visite", null)
                        .WithMany("Photos")
                        .HasForeignKey("VisiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestosVisites.Domain.Entities.Visite", b =>
                {
                    b.HasOne("RestosVisites.Domain.Entities.Restaurant", null)
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestosVisites.Domain.Entities.Visite", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
